spring.application.name=sistemaFuncionario_estudo

spring.datasource.url=jdbc:mysql://localhost:3306/funcionario_estudo
spring.datasource.username=root
spring.datasource.password=pizcyi95

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true